branch-defaults:
  default:
    environment: image-filter-env
    group_suffix: null
global:
  application_name: image-filter-service
  default_platform: Node.js 20 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  profile: default
  sc: null
